// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUHWdZa3Et3z3RsHLh7c2L3eqqBtn3uRA',
    appId: '1:704871662587:web:bb879107e5c10427d0815e',
    messagingSenderId: '704871662587',
    projectId: 'baseweb-345117',
    authDomain: 'baseweb-345117.firebaseapp.com',
    storageBucket: 'baseweb-345117.appspot.com',
    measurementId: 'G-NRPY5Z0R5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN3uBhmuAZ7D7553fQ3vP8wfR1odXj7R8',
    appId: '1:704871662587:android:624424676a9fd43cd0815e',
    messagingSenderId: '704871662587',
    projectId: 'baseweb-345117',
    storageBucket: 'baseweb-345117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVCeBcOrpezfPgljEn-OsDXS-YmsGHnUI',
    appId: '1:704871662587:ios:7a976cabf286653ad0815e',
    messagingSenderId: '704871662587',
    projectId: 'baseweb-345117',
    storageBucket: 'baseweb-345117.appspot.com',
    iosClientId: '704871662587-c1653323m48idvjjv1makalonptg6v5c.apps.googleusercontent.com',
    iosBundleId: 'com.wehire.toilet',
  );
}
